### ISSUE TITLE
Produce "active" and "active_diff"

### ISSUE THREAD

**Issue by impredicative** [axisbits/covid-api#1]
I'm actively and reasonably using the API. Thank you for providing it. The following keys are requested:

* active = confirmed - deaths - recovered
* active_diff = ...

**Comment by elitemaks** [comment]
Hi @impredicative, good suggestion, will do and update you.

**Comment by impredicative** [comment]
I will no longer be using this API since it has proved unreliable.

**Comment by elitemaks** [comment]
@impredicative done. If you have further suggestions, please let us know
