### ISSUE TITLE
Country only data

### ISSUE THREAD

**Issue by gregchak** [axisbits/covid-api#11]
Would it be possible to modify or create a new endpoint the returns country only data?  For example, if I just want stats on the US for 7/7/2020, the request to `/reports?iso=USA&date=2020-07-07` returns all the region and city data too.  The same could be said for just needing Region info, but that response payload is small enough that its not too big of a deal.

**Comment by elitemaks** [comment]
@gregchak I see a possible issue here. For example, in the data CSV from John Hopkins, there is a record - "Province - French Guiana, Country - France". If we combine all regions and display a total for France then this region will be counted too. But it's an overseas territory and not a region of France, so it might be misleading. The same is for China - Hong Kong - which causes a lot of debates on the Johns Hopkins GitHub page. 
So, at the moment I'm not sure how to separate regions of the country and various overseas and dependent territories.

**Comment by gregchak** [comment]
I can see that as an issue.  Very good point.  Especially if the overseas and dependent territories are not tagged/labelled as such in the data.

**Comment by elitemaks** [comment]
Not possible to implement with the current CSV structure
