### ISSUE TITLE
Thank you once again

### ISSUE THREAD

**Issue by impredicative** [axisbits/covid-api#17]
In these difficult times, I want to thank you yet again for the service you have provided. I continue to find the API useful. I hope you have chosen and executed the path that works for you, whether it be fight or flight.

**Comment by elitemaks** [comment]
Hi @impredicative , thank you for kind words. It's hard times for our team now, we all try to support our country as we can. 
Oh I see our API has not been updated for several days, we will fix it and will continue to provide this service.

**Comment by impredicative** [comment]
Hi @elitemaks , the API looks to be working well. I hope that your team has been able to move to safety. Regards.

**Comment by elitemaks** [comment]
Thanks! If you have any issues in the future - please report.
