### ISSUE TITLE
Data not updated

### ISSUE THREAD

**Issue by impredicative** [axisbits/covid-api#2]
The last update was for March 15. There is no data for March 16 even though it has been over 16 hours UTC since March 16 elapsed. What's going on? Is this a human exercised data pipeline or is it automated?

**Comment by elitemaks** [comment]
Hi @impredicative , thank you for reporting! It is automated, we will check it soon and get back to you.

**Comment by impredicative** [comment]
I will no longer be using this API since it has proved unreliable.

**Comment by elitemaks** [comment]
@impredicative sorry to hear that. Auto-update has failed because of the inconsistency of territories names in the data files. We fixed that issue and made sure that such errors are handled properly. 
Now data is fully updated.

**Comment by impredicative** [comment]
Thank you for fixing. I will try it again.
