### ISSUE TITLE
Clarification about Active and Recovered data for US and Canada

### ISSUE THREAD

**Issue by impredicative** [axisbits/covid-api#7]
For US and Canada, I see that the Recovered data for US and Canada is under a province named "Recovered" for both:

* https://covid-api.com/api/reports?date=2020-03-28&iso=USA&region_province=Recovered
* https://covid-api.com/api/reports?date=2020-03-28&iso=CAN&region_province=Recovered

This is fine, but just to be sure, is this how it is in the source? Either way, maybe the following statement in the readme needs to be updated:

> Data for recovered and active cases will not be provided for US states any longer, as Johns Hopkins CSSE will not update it. 

Does the following replacement make sense?

> Data for recovered cases for US and Canada cases at the state/province level is consolidated under a province named "Recovered". This is because Johns Hopkins CSSE does not update it at the state/province level for US and Canada.

**Comment by elitemaks** [comment]
@impredicative thank you for your help! You are correct, the data in the source files is structured like that. I will update the readme file, but, I'm not sure how accurate is this data for recovered. But, we have nothing to do with that, will hope Johns Hopkins CSSE provides accurate data.
